name: Layouts
favicon: null
layout_spectrum: 0
typography_spectrum: 0.34016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d2cc'
    - '#050504'
    - '#514f4f'
    - '#a5a29b'
    - '#a72a1b'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
